### ISSUE TITLE
Okio clears the Thread interrupt status

### ISSUE THREAD

**Issue by DrMetallius** [square/okio#475]
There is an issue in Okio similar to [issue #3945 in OkHttp](https://github.com/square/okhttp/issues/3945). The thread's interrupted state is not preserved in some places, and while it's great that this problem is resolved in the newest OkHttp release, the issue in Okio still prevents us from removing workarounds.

The place at fault is the method `throwIfReached` in `Timeout`. In there, the thread interruption state is cleared, but `InterruptedException` or its descendant is not thrown (`InterruptedIOException isn't one). The only way to detect that the thread was interrupted is to scan the exception message. I see this problem in both Java and Kotlin versions of the library.

Please fix this issue as well so we can remove the workarounds completely.

**Comment by swankjesse** [comment]
The fix is merged and just needs to be released.
https://github.com/square/okio/pull/467
https://github.com/square/okio/pull/468

**Comment by DrMetallius** [comment]
@swankjesse, that's good to know, thanks.

**Comment by DrMetallius** [comment]
@swankjesse, that's the problem, it doesn't fix the problematic place I described in the issue. I've seen those changes, but they missed the `throwIfReached` method.

**Comment by DrMetallius** [comment]
Finally removed the workarounds in our code, thanks! 👍

Just FYI, you were looking for a method which only checks the status of the thread without clearing it, it's `Thread.currentThread().isInterrupted()`. Clearing the interrupted state and immediately restoring it looks a little weird (although it definitely works!).
